/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/scene.glb -k -K 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/scene.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" position={[0.491, -0.115, -1.788]} rotation={[-Math.PI, 0.005, -Math.PI]} scale={3.193}>
          <group name="Armature">
            <primitive object={nodes.Hips} />
          </group>
          <skinnedMesh name="Wolf3D_Body" geometry={nodes.Wolf3D_Body.geometry} material={materials['Wolf3D_Body.001']} skeleton={nodes.Wolf3D_Body.skeleton} />
          <skinnedMesh name="Wolf3D_Hair" geometry={nodes.Wolf3D_Hair.geometry} material={materials['Wolf3D_Hair.001']} skeleton={nodes.Wolf3D_Hair.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Bottom" geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials['Wolf3D_Outfit_Bottom.001']} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Footwear" geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials['Wolf3D_Outfit_Footwear.001']} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
          <skinnedMesh name="Wolf3D_Outfit_Top" geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials['Wolf3D_Outfit_Top.001']} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
          <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials['Wolf3D_Eye.001']} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
          <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials['Wolf3D_Eye.001']} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
          <skinnedMesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials['Wolf3D_Skin.001']} skeleton={nodes.Wolf3D_Head.skeleton} morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences} />
          <skinnedMesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials['Wolf3D_Teeth.001']} skeleton={nodes.Wolf3D_Teeth.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences} />
        </group>
        <group name="Plane">
          <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.Floor} />
          <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials.Default} />
          <mesh name="Plane_3" geometry={nodes.Plane_3.geometry} material={materials.Wall} />
        </group>
        <mesh name="chair" geometry={nodes.chair.geometry} material={materials.LeatherExecutiveChair1} position={[0.482, 0.978, -1.616]} rotation={[-Math.PI / 2, 0, 3.141]} scale={0.914} />
        <group name="plant" position={[-4, 1.132, -3.752]}>
          <mesh name="mesh24448074" geometry={nodes.mesh24448074.geometry} material={materials.mat9} />
          <mesh name="mesh24448074_1" geometry={nodes.mesh24448074_1.geometry} material={materials.mat21} />
          <mesh name="mesh24448074_2" geometry={nodes.mesh24448074_2.geometry} material={materials.mat20} />
        </group>
        <group name="table" position={[0.962, 0, -4.319]} rotation={[0, -1.565, 0]}>
          <mesh name="Plane001_Plane002_BlackWood" geometry={nodes.Plane001_Plane002_BlackWood.geometry} material={materials.BlackWood} />
          <mesh name="Plane001_Plane002_BlackWood_1" geometry={nodes.Plane001_Plane002_BlackWood_1.geometry} material={materials.GrayPlastic} />
          <mesh name="Plane001_Plane002_BlackWood_2" geometry={nodes.Plane001_Plane002_BlackWood_2.geometry} material={materials.BlackCoatSteel} />
          <mesh name="Plane001_Plane002_BlackWood_3" geometry={nodes.Plane001_Plane002_BlackWood_3.geometry} material={materials.WhiteSteelScrew} />
          <mesh name="Plane001_Plane002_BlackWood_4" geometry={nodes.Plane001_Plane002_BlackWood_4.geometry} material={materials.BlackPlastic} />
        </group>
        <mesh name="imac" geometry={nodes.imac.geometry} material={materials['Mat.001']} position={[0.492, 2.418, -4.745]} rotation={[Math.PI, -1.561, Math.PI]} />
        <mesh name="mouse" geometry={nodes.mouse.geometry} material={materials.Material} position={[1.456, 2.418, -3.807]} />
        <group name="pikachu" position={[2.729, 3.03, -4.205]} rotation={[-Math.PI, 0.581, -Math.PI]}>
          <mesh name="mesh1465871970" geometry={nodes.mesh1465871970.geometry} material={materials.mat12} />
          <mesh name="mesh1465871970_1" geometry={nodes.mesh1465871970_1.geometry} material={materials['mat20.001']} />
          <mesh name="mesh1465871970_2" geometry={nodes.mesh1465871970_2.geometry} material={materials.mat23} />
          <mesh name="mesh1465871970_3" geometry={nodes.mesh1465871970_3.geometry} material={materials.mat8} />
          <mesh name="mesh1465871970_4" geometry={nodes.mesh1465871970_4.geometry} material={materials['mat21.001']} />
        </group>
        <mesh name="keyboard" geometry={nodes.keyboard.geometry} material={materials.lambert3SG} position={[0.236, 2.413, -3.888]} />
        <mesh name="screen" geometry={nodes.screen.geometry} material={materials['Mat.001']} position={[0.492, 2.418, -4.745]} rotation={[Math.PI, -1.561, Math.PI]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.glb')
